### ISSUE TITLE
Use HTML's native Dialogs for a new AtomDialog element

### ISSUE THREAD

**Issue by nathanaelhoun** [Atom-Fundation/Atom#30]
The [HTML5 <dialog> element](https://developer.mozilla.org/fr/docs/Web/HTML/Element/dialog) (with [very good support - caniuse](https://caniuse.com/dialog) could be used to create a new dialog/modal element for Atom, with some vanilla JS and CSS to improve the usage.

Some features could be:
- [ ] Automatically add a close button (if an element with `.a-dialog-close` is not already present - if so, use this one)
- [ ] Automatically close the modal if clicking outside
- [ ] Add some pretty CSS and opening/closing animations (with respects of [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion))
- [ ] ... ?

<details><summary>Here is a PoC :</summary>

Application HTML
```html
<menu>
    <button class="a-btn a-half-primary" data-a-for-dialog="welcome-dialog">Ouvrir la boîte de dialogue</button>
</menu>

<dialog class="a-dialog" id="welcome-dialog">
    <h2>Salutations, à tous et à toutes !</h2>

    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam temporibus at doloribus est enim possimus itaque
        officiis eligendi soluta reiciendis, asperiores, quisquam ea amet rerum eum, excepturi harum odit ullam.</p>

    <div class="col-md-4 a-input-group">
        <input class="a-input" type="text" name="random-input" id="random-input">
        <label for="random-input">Un champ input</label>
    </div>

    <button>Bouton qui ne fait rien</button>
</dialog>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        AtomAutoBindButtonsDialogs();
    });
</script>
```

Atom's JS
```js
class AtomModalDialog {
    /**
     * @param {HTMLDialogElement} dialog
     */
    static initEventListeners(dialog) {
        // Add closing button
        dialog.insertAdjacentHTML("afterbegin", '<button class="a-dialog-close"></button>');

        const closeButton = dialog.querySelector(".a-dialog-close") ?? document.createElement("button");
        closeButton.title = "Fermer";
        closeButton.innerHTML = closeButton.innerHTML || '<i class="fa-solid fa-xmark"></i>';
        closeButton.classList.add("a-dialog-close");
        dialog.insertAdjacentElement("afterbegin", closeButton);
        closeButton.addEventListener("click", () => dialog.close());

        // Closing dialog if click if outside
        dialog.addEventListener("click", (ev) => {
            if (ev.target.tagName !== "DIALOG") {
                return; //This prevents issues with forms
            }

            const rect = ev.target.getBoundingClientRect();
            const clickedInDialog =
                rect.top <= ev.clientY &&
                ev.clientY <= rect.top + rect.height &&
                rect.left <= ev.clientX &&
                ev.clientX <= rect.left + rect.width;

            if (clickedInDialog === false) {
                return ev.target.close();
            }
        });
    }
}

function atomAutoBindButtonsDialogs() {
    document.querySelectorAll("button[data-a-for-dialog]").forEach((button) => {
        /** @const {HTMLDialogElement} dialog */
        const dialog = document.getElementById(button.dataset.aForDialog);

        button.addEventListener("click", () => dialog.showModal());
        AtomModalDialog.initEventListeners(dialog)
    });
};
```

Atom's CSS
````scss
.a-dialog {
    --a-dialog-padding: 15px;

    padding: var(--a-dialog-padding);
    padding-top: calc(2 * var(--a-dialog-padding));
    max-width: 60ch;

    &[open] {
        animation: a-top-2-center 0.2s ease-out;
    }    

    &::backdrop {
        background-color: rgba(128, 128, 128, 0.6);
        backdrop-filter: blur(3px);
    }    

    .a-dialog-close {
        position: absolute;
        top: var(--a-dialog-padding);
        right: var(--a-dialog-padding);
    
        font-size: 1.5em;
        line-height: 1;
        padding: 0;
    
        background-color: transparent;
        opacity: 0.75;
        border: 0;

        &:hover {
            opacity: 1;
        }
    }    
}
```
</details>

**Comment by tdelavoux** [comment]
I updated the CSS for better native UI of a-dialog (remove border and add border-radius). 
Add animation on backdrop color from transpatrent to dark but it do not fit with backdrop-filter (shaking effect) t. It might be removed and  use backdrop blur transition instead to keep the glassy effect : 

```CSS
@keyframes a-bg-transition {
    from {backdrop-filter: blur(0px);}
    to {backdrop-filter: blur(4px);}
}
```

### Proposition 
```CSS 
.a-dialog {
    --a-dialog-padding: 15px;

    padding: var(--a-dialog-padding);
    padding-top: calc(2 * var(--a-dialog-padding));
    max-width: 60ch;
    border-radius:8px;
    border:none;

    &[open] {
        animation: a-top-2-center 0.30s ease-out;
    }    

    &::backdrop {
        background-color: rgba( 38, 38, 38, 0.55 );
        /*backdrop-filter: blur(2px);*/
        animation: a-bg-transition 0.30s ease-out;
    }    

    .a-dialog-close {
        position: absolute;
        top: var(--a-dialog-padding);
        right: var(--a-dialog-padding);
    
        font-size: 1.5em;
        line-height: 1;
        padding: 0;
    
        background-color: transparent;
        opacity: 0.75;
        border: 0;

        &:hover {
            opacity: 1;
        }
    }    
}

@keyframes a-bg-transition {
    from {background-color: transparent}
    to {background-color: rgba( 38, 38, 38, 0.55 );}
}


@keyframes a-top-2-center{
    from {
        transform: translateY(-15%);
    }
    to {
        transform: translateY(0%);
    }
}
```

### improvements ideas
1. Give option array on constructor to define some custom values as width, animation effect ... 
2. Close transition effect
